language: java
jdk: oraclejdk8
dist: trusty
install: ./.travis.install.sh
addons:
  google-chrome: latest
deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
    - /^\d+\.\d+$/
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-board

